import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Expense } from "@/types";
import { formatCurrency, formatDate } from "./utils";

export interface PDFExportData {
  monthLabel: string;
  userName?: string;
  totalContribution: number;
  totalExpenses: number;
  fixedExpenses: number;
  variableExpenses: number;
  remainingBalance: number;
  expenses: Expense[];
  currency?: string;
}

export function exportExpensesToPDF(data: PDFExportData): void {
  const doc = new jsPDF();
  const currency = data.currency || "₹";

  // Brand Header Bar (Emerald Green)
  doc.setFillColor(16, 185, 129); // #10B981
  doc.rect(0, 0, 210, 24, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("FINTRACK — FINANCIAL STATEMENT", 14, 16);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(data.monthLabel, 196, 16, { align: "right" });

  // Summary Metadata
  let currentY = 34;
  doc.setTextColor(15, 23, 42); // slate-900
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Summary Overview", 14, currentY);

  currentY += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  // Draw 2x3 Summary Card Grid
  const summaryItems = [
    { label: "Total Contributions:", val: formatCurrency(data.totalContribution, currency) },
    { label: "Total Expenses:", val: formatCurrency(data.totalExpenses, currency) },
    { label: "Fixed Recurring Bills:", val: formatCurrency(data.fixedExpenses, currency) },
    { label: "Variable Expenses:", val: formatCurrency(data.variableExpenses, currency) },
    { label: "Remaining Balance:", val: formatCurrency(data.remainingBalance, currency) },
    { label: "Total Transactions:", val: `${data.expenses.length} records` },
  ];

  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, currentY, 182, 32, 3, 3, "FD");

  summaryItems.forEach((item, index) => {
    const col = index % 2;
    const row = Math.floor(index / 2);
    const x = 18 + col * 92;
    const y = currentY + 8 + row * 9;

    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);
    doc.text(item.label, x, y);

    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text(item.val, x + 48, y);
  });

  currentY += 40;

  // Itemized Transaction Table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text("Itemized Transaction Record", 14, currentY);

  currentY += 4;

  const tableBody = data.expenses.map((exp) => [
    formatDate(exp.date),
    exp.title,
    exp.category,
    exp.paymentMethod,
    formatCurrency(exp.amount, currency),
  ]);

  autoTable(doc, {
    startY: currentY,
    head: [["Date", "Expense Title", "Category", "Payment Method", "Amount"]],
    body: tableBody,
    theme: "striped",
    headStyles: {
      fillColor: [16, 185, 129],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    styles: {
      fontSize: 9,
      cellPadding: 3,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
  });

  // Footer page number
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Generated by FinTrack App — Page ${i} of ${pageCount}`,
      105,
      290,
      { align: "center" }
    );
  }

  const cleanMonth = data.monthLabel.replace(/\s+/g, "_");
  doc.save(`Financial_Report_${cleanMonth}.pdf`);
}
